name: Update Mod Data

on:
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-mod-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch mod data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_mods.py

      - name: Publish to mod_data branch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan mod_data_tmp
          git rm -rf .
          git add mods.json
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "chore: update mod data [${TIMESTAMP}]"
          git push origin HEAD:mod_data --force
